In [13]:
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd
from datetime import datetime

def select_list(url,params,table_class):
    head = {
       'User-Agent':'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36'
    }
    res = requests.post(url,headers=head,params=params)
    soup = bs(res.text,'lxml')
    tr_list = soup.select('.'+table_class+' tr')
    td_list = [list(map(lambda x:x.text.strip(),td)) for td in [tr.select('td')[1:] for tr in tr_list[1:]]]
    return td_list

In [9]:
datetime.today().strftime('%Y%m%d')

'20180112'

In [18]:
def kac_sch_list(port='GMP'):
    ## 한국공항공사 데이터
    params = {
        'airPort':port,
        'stHour':'01',
        'stMinute':'00',
        'edHour':'24',
        'edMinute':'55',
        'airType':'',
        'airLine':'ZE',
        'airLineNum':''
    }
    kac_list = []
    ## 한국공항공사 출발
    url = 'https://www.airport.co.kr/gimpo/extra/liveSchedule/liveScheduleList/layOut.do?langType=1&inoutType=OUT&cid=2015102611043202364&menuId=8'
    kac_list.extend([['D',d[0][2:],d[1],d[2],d[5],d[6]] for d in select_list(url,params,'table-responsive')])
    ## 한국공항공사 도착
    url = 'https://www.airport.co.kr/gimpo/extra/liveSchedule/liveScheduleList/layOut.do?langType=1&inoutType=IN&cid=2015102611052578964&menuId=10'
    kac_list.extend([['A',d[0][2:],d[1],d[2],d[5],d[6]] for d in select_list(url,params,'table-responsive')])
    df = pd.DataFrame(kac_list,columns=['type','flt','from','to','tm','gate'])
    df.to_csv(port+'_'+datetime.today().strftime('%Y%m%d')+'.csv')
    return df

In [17]:
def icn_sch_list():
    today = datetime.today().strftime('%Y%m%d')
    ## 인천공항공사 데이터
    params = {
        'A':'A',
        'FROM_TIME':today+'0000',
        'TO_TIME':today+'2400',
        'AIRLINE':'ZE'
    }
    icn_list = []
    ## 인천공항공사 출발
    url = 'http://www.airport.kr/pa/aps/pac111000List.do'
    icn_list.extend([['D',d[0][2:],d[1],d[2],d[4],d[6]]
                     for d in select_list(url,params,'tablelist2')])
    ## 인천공항공사 도착
    url = 'http://www.airport.kr/pa/aps/pac112000List.do'
    icn_list.extend([['A',d[0][2:],d[1],d[2],d[4],d[5]]
                     for d in select_list(url,params,'tablelist2')])
    df = pd.DataFrame(icn_list,columns=['type','flt','from','to','tm','gate'])
    df.to_csv('ICN'+datetime.today().strftime('%Y%m%d')+'.csv')
    return df

In [19]:
kac_sch_list()

   type   flt     from       to   tm gate
0     D   201  06 : 20  06 : 30  국내선   13
1     D   203  06 : 45  07 : 55  국내선    3
2     D   251  06 : 50  07 : 10  국내선
3     D   207  09 : 50  10 : 45  국내선   13
4     D   253  10 : 20  11 : 40  국내선   13
5     D  9887  11 : 00  11 : 30  국제선   34
6     D   209  11 : 15  11 : 15  국내선    1
7     D   261  12 : 15  12 : 15  국내선    2
8     D   257  12 : 50  12 : 50  국내선   13
9     D   213  12 : 55           국내선
10    D   215  13 : 50           국내선
11    D   217  14 : 45           국내선
12    D   219  15 : 50           국내선
13    D   221  16 : 55           국내선
14    D   223  18 : 20  18 : 20  국내선   13
15    D   225  19 : 25           국내선
16    D   227  19 : 45           국내선
17    D   229  20 : 00           국내선
18    D   231  20 : 20           국내선
19    A   222  01 : 40  01 : 40  국내선
20    A   224  01 : 50  01 : 50  국내선
21    A  226A  02 : 45  02 : 45  국내선
22    A   202  09 : 15  10 : 11  국내선
23    A   258  09 : 50  11 : 13  국내선
24    A   206  10 : 40  10 : 40  국내선
25    A   208  11 : 10  11 : 10  국내선
26    A   262  11 : 40  11 : 40  국내선
27    A   254  13 : 00           국내선
28    A   210  13 : 15           국내선
29    A   212  14 : 10           국내선
30    A   260  15 : 10           국내선
31    A   216  16 : 10           국내선
32    A   252  16 : 30           국내선
33    A  9888  17 : 10           국제선
34    A   218  18 : 40           국내선
35    A   220  19 : 05           국내선
36    A   222  19 : 25           국내선
37    A   224  19 : 45           국내선
38    A   226  20 : 55           국내선
39    A   228  21 : 35  21 : 35  국내선
40    A   230  22 : 35           국내선

In [20]:
icn_sch_list()

   type   flt   from     to  tm gate
0     D   633  06:30  06:53  T1   33
1     D   621  07:25  07:42  T1   24
2     D   881  07:55  08:28  T1   16
3     D   601  08:40  09:00  T1    9
4     D   611  09:05  09:35  T1  108
5     D   641  09:35  09:35  T1   28
6     D   617  09:40  10:09  T1  114
7     D   931  09:10  10:25  T1  125
8     D   631  11:30  11:30  T1   28
9     D   623  13:30  13:30  T1   38
10    D   613  14:35  14:35  T1  122
11    D   651  14:45  14:45  T1   18
12    D  9631  14:15  15:10  T1  126
13    D   615  15:25  15:25  T1   33
14    D   603  15:40  15:40  T1   37
15    D   643  15:50  15:50  T1   38
16    D   511  17:05  17:05  T1  127
17    D   591  18:20  18:20  T1  103
18    D   501  19:00  19:00  T1  102
19    D   503  20:35  20:35  T1   18
20    D   593  20:45  20:45  T1  131
21    D   541  20:50  20:50  T1  130
22    D   513  20:55  20:55  T1   14
23    D   505  21:00  21:00  T1  102
24    D   595  21:45  21:45  T1  125
25    A   592  05:00  05:02  T1   33
26    A   512  06:20  05:32  T1   24
27    A   502  06:40  06:20  T1   37
28    A   594  06:00  06:46  T1  108
29    A   596  08:35  08:27  T1  103
30    A   504  08:10  08:43  T1  114
31    A   542  07:30  08:51  T1  125
32    A   506  08:30  09:02  T1   28
33    A   514  10:20  10:23  T1   38
34    A   634  12:25  11:49  T1   18
35    A   642  13:30  13:30  T1   37
36    A   612  13:50  13:50  T1  122
37    A   882  14:20  14:20  T1   38
38    A   602  14:30  14:30  T1    9
39    A   622  14:35  14:35  T1  127
40    A   618  14:35  14:35  T1   33
41    A   632  16:55  16:55  T1   45
42    A   932  18:05  18:05  T1  102
43    A   614  19:35  19:35  T1   18
44    A   652  19:40  19:40  T1  130
45    A   644  20:05  20:05  T1  125
46    A   624  20:05  20:05  T1   14
47    A   616  20:10  20:10  T1  102
48    A  9632  19:55  20:40  T1   36
49    A   604  21:35  21:35  T1   27